FROM node:22-alpine

ENV NODE_ENV=production

# Install basic tools and shells
RUN apk add --no-cache bash zsh tcsh curl gnupg ca-certificates git

# Install scripting languages and runtime environments
RUN apk add --no-cache python3 py3-pip perl ruby php openjdk21-jdk lua5.4 R gawk tcl expect

# Install global Node.js tools
RUN npm install -g typescript ts-node taylored

WORKDIR /usr/src/runner
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 2979-3000
CMD ["node", "runner.js"]
